# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-x
  namespace: project-x
  labels:
    app.kubernetes.io/name: project-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: project-x
      app.kubernetes.io/part-of: project-x
  template:
    metadata:
      labels:
        app.kubernetes.io/name: project-x
        app.kubernetes.io/part-of: project-x
    spec:
      containers:
        - name: project-x
          image: registry.dev.svc.cluster.local:5000/project-x:0.1.0
          ports:
            - containerPort: 8000
              name: project-x-api
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: project-x-api
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: project-x-api
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
