# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/

apiVersion: v1
kind: Service
metadata:
  name: project-x
spec:
  type: ClusterIP
  ports:
    - name: project-x
      port: 80
      protocol: TCP
      targetPort: project-x-api
