# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1/

apiVersion: v1
kind: ConfigMap
metadata:
  name: project-x
  namespace: project-x
  labels:
    app.kubernetes.io/name: project-x
    app.kubernetes.io/part-of: project-x
data:
  config.toml: |
    [project-x.uvicorn]
    host = "0.0.0.0"
    port = 8000
    log-level = "debug"
