kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: the-podmaster
  namespace: project-x
subjects:
  - kind: User
    name: professorX
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: the-podmaster
  apiGroup: rbac.authorization.k8s.io
