# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
