# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/
# https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

apiVersion: v1
kind: Pod
metadata:
  name: project-x
  namespace: project-x
  labels:
    app.kubernetes.io/name: project-x
    app.kubernetes.io/part-of: project-x
spec:
  containers:
    - name: project-x
      image: registry.dev.svc.cluster.local:5000/project-x:0.4.0
      env:
        - name: PROJECT_X_UVICORN_HOST
          value: "0.0.0.0"
        - name: PROJECT_X_UVICORN_PORT
          value: "8000"
        - name: PROJECT_X_UVICORN_LOG_LEVEL
          value: "debug"
      ports:
        - containerPort: 8000
          name: project-x-api
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /health
          port: project-x-api
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /health
          port: project-x-api
        initialDelaySeconds: 5
        periodSeconds: 5
      volumeMounts:
        - mountPath: "/mnt"
          name: project-x-pv
  initContainers:
    - name: populate-quotes
      image: registry.dev.svc.cluster.local:5000/project-x:0.4.0
      command:
        - project-x
        - populate-quotes
      volumeMounts:
        - mountPath: "/mnt"
          name: project-x-pv
  volumes:
    - name: project-x-pv
      persistentVolumeClaim:
        claimName: project-x
