# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/

apiVersion: v1
kind: Secret
metadata:
  name: project-x
  namespace: project-x
  labels:
    app.kubernetes.io/name: project-x
    app.kubernetes.io/part-of: project-x
type: Opaque
data:
  config.toml: |
    W3Byb2plY3QteC51dmljb3JuXQpob3N0ID0gIjAuMC4wLjAiCnBvcnQgPSA4MDAwCmxvZy1sZXZl
    bCA9ICJkZWJ1ZyIKCg==
