# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/

apiVersion: v1
kind: Service
metadata:
  name: project-x-headless
  namespace: project-x
  labels:
    app.kubernetes.io/name: project-x
    app.kubernetes.io/part-of: project-x
spec:
  ports:
    - name: project-x
      port: 80
  clusterIP: None
  selector:
    app.kubernetes.io/name: project-x
    app.kubernetes.io/part-of: project-x
