# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/
# https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    app.kubernetes.io/name: proxy
    app.kubernetes.io/part-of: proxy
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
      - containerPort: 80
        name: nginx
        protocol: TCP
