# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/

apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app.kubernetes.io/name: proxy
    app.kubernetes.io/part-of: proxy
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: nginx
