# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/
# https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

apiVersion: v1
kind: Secret
metadata:
  name: project-x
  namespace: project-x
  labels:
    app.kubernetes.io/name: project-x
    app.kubernetes.io/part-of: project-x
type: Opaque
data:
  uvicorn_host: MC4wLjAuMA==
  uvicorn_port: OTAwMA==
  uvicorn_log_level: aW5mbw==
