# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/
# https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

apiVersion: v1
kind: Secret
metadata:
  name: project-x
  namespace: project-x
  labels:
    app.kubernetes.io/name: project-x
    app.kubernetes.io/part-of: project-x
type: Opaque
data:
  PROJECT_X_UVICORN_HOST: MC4wLjAuMA==
  PROJECT_X_UVICORN_PORT: OTAwMA==
  PROJECT_X_UVICORN_LOG_LEVEL: aW5mbw==
