# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-x
  namespace: project-x
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
